#taskreact:
#    resource: "@TaskreactBundle/Resources/config/routing.yml"
#    prefix:   /
    
taskreact:
    resource: "@TaskreactBundle/Resources/config/routing.yml"
    prefix:   /tasks   

    
 
    
#taskreact_list:
#    path:      /tasks/{condition}/
#    defaults: { _controller: TaskreactBundle:Task:list, condition: active }
#    #options: {name: genus_show_notes}
#    requirements:
#        condition: active|archive|all
        
        

   

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
