taskreact_homepage:
    path:     /
    defaults: { _controller: TaskreactBundle:Task:index }
    #defaults: { _controller: TaskreactBundle:Task:list, _condition: active }
    #requirements:
    #    _condition: active|archive

taskreact_list:
    path:      /{condition}/
    defaults: { _controller: TaskreactBundle:Task:list, condition: all }
    #options: {name: genus_show_notes}
    requirements:
        condition: active|archive|all

taskreact_create:
    path:      /create/
    defaults: { _controller: TaskreactBundle:Task:create }
    
taskreact_update:
    path:      /update/
    defaults: { _controller: TaskreactBundle:Task:update }    
    
taskreact_delete:
    path:      /delete/
    defaults: { _controller: TaskreactBundle:Task:delete }     
    
        
